#!/bin/bash

echo -n "Strobe Frequency? (50|60): "
read fs

echo -n "Crystal Frequency? (10|12|147): "
read fx

while [ '1' == '1' ]
do
    echo "[ENTER] to program, CTRL/C to quit"
    read x
    echo "Programming..."
    make install F_STROBE=${fs} F_XTAL=${fx}
done
