#!/bin/bash

not_done=1

while [ "$not_done" == '1' ]
do
    echo -n "Program another? [Y/n] "
    read x
    if [ "$x" == 'n' ]
    then
        not_done=0
    else
        echo "Programming..."
        make install
    fi
done
